package io.github.xyzboom.aiFuzzer.translator.pytorch

import io.github.oshai.kotlinlogging.KotlinLogging
import io.github.xyzboom.aiFuzzer.ir.*
import io.github.xyzboom.aiFuzzer.ir.types.*
import io.github.xyzboom.aiFuzzer.translator.UirTranslator

private val log = KotlinLogging.logger {}

/**
 * UIR 到 PyTorch Python 代码的翻译器。
 *
 * 将 UirProgram 翻译为 `torch.nn.Module` + `torch.compile` 形式的 Python 代码。
 *
 * @param dtype 默认数据类型
 * @param device 执行设备（"cpu" 或 "cuda"）
 * @param compileMode torch.compile 模式
 */
class PytorchTranslator(
    private val dtype: String = "float32",
    private val device: String = "cpu",
    private val compileMode: String = "default",
) : UirTranslator<UirProgram, String> {

    companion object {
        /**
         * UIR 算子到 PyTorch API 的映射。
         */
        val opMapping: Map<UirOpKind, String> = mapOf(
            // 元素级二元
            UirOpKind.ADD to "torch.add",
            UirOpKind.SUBTRACT to "torch.sub",
            UirOpKind.MULTIPLY to "torch.mul",
            UirOpKind.DIVIDE to "torch.div",
            UirOpKind.MAXIMUM to "torch.maximum",
            UirOpKind.MINIMUM to "torch.minimum",
            UirOpKind.POWER to "torch.pow",

            // 矩阵乘法
            UirOpKind.MATMUL to "torch.matmul",

            // 卷积
            UirOpKind.CONV2D to "F.conv2d",

            // 一元激活
            UirOpKind.RELU to "F.relu",
            UirOpKind.SIGMOID to "torch.sigmoid",
            UirOpKind.TANH to "torch.tanh",
            UirOpKind.GELU to "F.gelu",
            UirOpKind.SILU to "F.silu",

            // 一元数学
            UirOpKind.NEG to "torch.neg",
            UirOpKind.ABS to "torch.abs",
            UirOpKind.EXP to "torch.exp",
            UirOpKind.LOG to "torch.log",
            UirOpKind.SQRT to "torch.sqrt",
            UirOpKind.CEIL to "torch.ceil",
            UirOpKind.FLOOR to "torch.floor",

            // SOFTMAX
            UirOpKind.SOFTMAX to "F.softmax",

            // 归约
            UirOpKind.REDUCE_SUM to "torch.sum",
            UirOpKind.REDUCE_MEAN to "torch.mean",
            UirOpKind.REDUCE_MAX to "torch.max",
            UirOpKind.REDUCE_MIN to "torch.min",

            // 形状变换
            UirOpKind.RESHAPE to "torch.reshape",
            UirOpKind.TRANSPOSE to "torch.transpose",
            UirOpKind.SQUEEZE to "torch.squeeze",
            UirOpKind.UNSQUEEZE to "torch.unsqueeze",

            // 拼接/分割
            UirOpKind.CONCAT to "torch.cat",
            UirOpKind.SPLIT to "torch.split",

            // 索引
            UirOpKind.GATHER to "torch.gather",
            UirOpKind.STRIDED_SLICE to "torch.slice_scatter",

            // 广播/填充
            UirOpKind.BROADCAST_TO to "torch.broadcast_to",
            UirOpKind.TILE to "torch.tile",

            // 类型转换
            UirOpKind.CAST to "torch.Tensor.to",

            // 常数生成
            UirOpKind.ARANGE to "torch.arange",
            UirOpKind.FULL to "torch.full",
            UirOpKind.ONES to "torch.ones",
            UirOpKind.ZEROS to "torch.zeros",

            // 三角矩阵
            UirOpKind.TRIL to "torch.tril",
            UirOpKind.TRIU to "torch.triu",

            // 适配算子
            UirOpKind.EXPAND_DIMS to "torch.unsqueeze",
        )

        /**
         * PyTorch dtype 名称映射。
         */
        val dtypeMapping = mapOf(
            "float32" to "torch.float32",
            "float64" to "torch.float64",
            "float16" to "torch.float16",
            "int32" to "torch.int32",
            "int64" to "torch.int64",
            "int16" to "torch.int16",
            "int8" to "torch.int8",
            "uint8" to "torch.uint8",
            "bool" to "torch.bool",
        )
    }

    override fun translate(element: UirProgram): String {
        log.debug { "开始翻译 UIR 程序到 PyTorch: ${element.graphs.size} 个图" }
        val builder = StringBuilder()

        // 生成文件头
        builder.appendLine("# Auto-generated by aiFuzzer PyTorch translator")
        builder.appendLine()

        // 导入
        builder.appendLine("import torch")
        builder.appendLine("import torch.nn as nn")
        builder.appendLine("import torch.nn.functional as F")
        builder.appendLine()

        // 翻译每个图
        for ((idx, graph) in element.graphs.withIndex()) {
            translateGraph(builder, graph, idx)
        }

        // IMPORTANT: 不要使用 if __name__ == "__main__" 保护，因为 daemon 会直接 exec 脚本
        builder.appendLine("# Main execution")

        // 实例化模块并编译（只编译不推理）
        builder.appendLine("model = TestModule_0()")
        builder.appendLine("try:")
        builder.appendLine("    compiled = torch.compile(model, mode=\"$compileMode\")")
        builder.appendLine("except Exception as e:")
        builder.appendLine("    print(f'torch.compile failed: {e}')")
        builder.appendLine("    raise")

        builder.appendLine()
        builder.appendLine("print('Module built successfully')")

        return builder.toString()
    }

    /**
     * 翻译单个计算图为 nn.Module。
     */
    private fun translateGraph(builder: StringBuilder, graph: UirGraph, graphIdx: Int) {
        val className = "TestModule_$graphIdx"
        builder.appendLine("class $className(nn.Module):")

        // 构造函数
        builder.appendLine("    def __init__(self):")
        builder.appendLine("        super().__init__()")

        // forward 函数
        val params = graph.inputs.map { it.valueId }.joinToString(", ")
        builder.appendLine("    def forward(self, $params):")

        // 值映射：valueId -> Python 变量名
        val valueMap = mutableMapOf<String, String>()

        // 图输入映射
        for (input in graph.inputs) {
            valueMap[input.valueId] = input.valueId
        }

        // 翻译每个节点
        for (node in graph.nodes) {
            translateNode(builder, node, valueMap)
        }

        // 返回输出
        val outputVars = graph.outputs.map { output ->
            valueMap[output.valueId] ?: output.valueId
        }
        if (outputVars.size == 1) {
            builder.appendLine("        return ${outputVars[0]}")
        } else {
            builder.appendLine("        return (${outputVars.joinToString(", ")})")
        }

        builder.appendLine()
    }

    /**
     * 翻译单个节点。
     */
    private fun translateNode(builder: StringBuilder, node: UirNode, valueMap: MutableMap<String, String>) {
        val op = node.op
        val pytorchFunc = opMapping[op] ?: "torch.${op.name.lowercase()}"

        // 生成调用代码
        val call = when (op) {
            // ===== 一元激活 =====
            UirOpKind.RELU -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.SIGMOID -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.TANH -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.GELU -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.SILU -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"

            // ===== 一元数学 =====
            UirOpKind.NEG -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.ABS -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.EXP -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.LOG -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.SQRT -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.CEIL -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.FLOOR -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"

            // ===== 二元运算 =====
            UirOpKind.ADD -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs.getOrElse(1) { node.inputs[0] }.valueId]})"
            UirOpKind.SUBTRACT -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs.getOrElse(1) { node.inputs[0] }.valueId]})"
            UirOpKind.MULTIPLY -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs.getOrElse(1) { node.inputs[0] }.valueId]})"
            UirOpKind.DIVIDE -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs.getOrElse(1) { node.inputs[0] }.valueId]})"
            UirOpKind.MAXIMUM -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs.getOrElse(1) { node.inputs[0] }.valueId]})"
            UirOpKind.MINIMUM -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs.getOrElse(1) { node.inputs[0] }.valueId]})"
            UirOpKind.POWER -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs.getOrElse(1) { node.inputs[0] }.valueId]})"

            // ===== 矩阵乘法 =====
            UirOpKind.MATMUL -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs[1].valueId]})"

            // ===== 卷积 =====
            UirOpKind.CONV2D -> {
                val stride = (node.attributes["stride"] as? UirIntAttr)?.value ?: 1
                val padding = (node.attributes["padding"] as? UirIntAttr)?.value ?: 0
                val dilation = (node.attributes["dilation"] as? UirIntAttr)?.value ?: 1
                val groups = (node.attributes["groups"] as? UirIntAttr)?.value ?: 1
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${valueMap[node.inputs[1].valueId]}, " +
                    "stride=$stride, padding=$padding, dilation=$dilation, groups=$groups)"
            }

            // ===== SOFTMAX =====
            UirOpKind.SOFTMAX -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: -1
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, dim=$axis)"
            }

            // ===== 归约 =====
            UirOpKind.REDUCE_SUM -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (node.attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, dim=$axis, keepdim=$keepdims)"
            }
            UirOpKind.REDUCE_MEAN -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (node.attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, dim=$axis, keepdim=$keepdims)"
            }
            UirOpKind.REDUCE_MAX -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (node.attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                // torch.max 返回 (values, indices)，需要取 values
                val inputVar = valueMap[node.inputs[0].valueId]!!
                if (keepdims) {
                    "torch.max($inputVar, dim=$axis, keepdim=True).values"
                } else {
                    "torch.max($inputVar, dim=$axis, keepdim=False).values"
                }
            }
            UirOpKind.REDUCE_MIN -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (node.attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                val inputVar = valueMap[node.inputs[0].valueId]!!
                if (keepdims) {
                    "torch.min($inputVar, dim=$axis, keepdim=True).values"
                } else {
                    "torch.min($inputVar, dim=$axis, keepdim=False).values"
                }
            }

            // ===== 形状变换 =====
            UirOpKind.RESHAPE -> {
                val outputShape = node.outputs[0].type.shape
                val shapeStr = shapeToPython(outputShape)
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ($shapeStr))"
            }
            UirOpKind.TRANSPOSE -> {
                // 默认交换最后两个维度
                val ndim = node.inputs[0].type.shape.dims.size
                if (ndim >= 2) {
                    "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ${ndim - 2}, ${ndim - 1})"
                } else {
                    "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, 0, 0)"
                }
            }
            UirOpKind.SQUEEZE -> {
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            }
            UirOpKind.UNSQUEEZE -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: 0
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, $axis)"
            }

            // ===== 拼接/分割 =====
            UirOpKind.CONCAT -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: 0
                val inputs = node.inputs.map { valueMap[it.valueId]!! }.joinToString(", ")
                "$pytorchFunc([$inputs], dim=$axis)"
            }
            UirOpKind.SPLIT -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: 0
                // 默认分成 2 份
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, 2, dim=$axis)"
            }

            // ===== 索引 =====
            UirOpKind.GATHER -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: 0
                val inputVar = valueMap[node.inputs[0].valueId]!!
                // 生成一个简单的 indices tensor
                val inputShape = node.inputs[0].type.shape
                val indicesShape = inputShape.dims.map { dim ->
                    if (dim.dimKind == UirDimKind.CONSTANT && dim.value != null) "min(${dim.value}, 1)" else "1"
                }.joinToString(", ")
                "torch.gather($inputVar, $axis, torch.zeros(($indicesShape), dtype=torch.int64, device=$inputVar.device))"
            }
            UirOpKind.STRIDED_SLICE -> {
                // 简化实现：取前半部分
                val inputVar = valueMap[node.inputs[0].valueId]!!
                "$inputVar[:${inputVar}.shape[0]//2]"
            }

            // ===== 广播/填充 =====
            UirOpKind.BROADCAST_TO -> {
                val outputShape = node.outputs[0].type.shape
                val shapeStr = shapeToPython(outputShape)
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, ($shapeStr))"
            }
            UirOpKind.TILE -> {
                val inputVar = valueMap[node.inputs[0].valueId]!!
                val ndim = node.inputs[0].type.shape.dims.size
                "$pytorchFunc($inputVar, [1] * $ndim)"
            }

            // ===== 类型转换 =====
            UirOpKind.CAST -> {
                val targetDtype = dtypeMapping[dtype] ?: "torch.float32"
                "${valueMap[node.inputs[0].valueId]}.to($targetDtype)"
            }

            // ===== 常数生成 =====
            UirOpKind.ARANGE -> {
                val outputShape = node.outputs[0].type.shape
                val totalSize = outputShape.dims.fold(1) { acc, dim ->
                    acc * (if (dim.dimKind == UirDimKind.CONSTANT) (dim.value ?: 1) else 1)
                }
                "$pytorchFunc(0, $totalSize, dtype=${dtypeMapping[dtype] ?: "torch.float32"}, device=\"$device\")"
            }
            UirOpKind.FULL -> {
                val outputShape = node.outputs[0].type.shape
                val shapeStr = shapeToPython(outputShape)
                "$pytorchFunc(($shapeStr), 0.0, dtype=${dtypeMapping[dtype] ?: "torch.float32"}, device=\"$device\")"
            }
            UirOpKind.ONES -> {
                val outputShape = node.outputs[0].type.shape
                val shapeStr = shapeToPython(outputShape)
                "$pytorchFunc(($shapeStr), dtype=${dtypeMapping[dtype] ?: "torch.float32"}, device=\"$device\")"
            }
            UirOpKind.ZEROS -> {
                val outputShape = node.outputs[0].type.shape
                val shapeStr = shapeToPython(outputShape)
                "$pytorchFunc(($shapeStr), dtype=${dtypeMapping[dtype] ?: "torch.float32"}, device=\"$device\")"
            }

            // ===== 三角矩阵 =====
            UirOpKind.TRIL -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"
            UirOpKind.TRIU -> "$pytorchFunc(${valueMap[node.inputs[0].valueId]})"

            // ===== 适配算子 =====
            UirOpKind.EXPAND_DIMS -> {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: 0
                "$pytorchFunc(${valueMap[node.inputs[0].valueId]}, $axis)"
            }

            // ===== 默认 =====
            else -> {
                log.warn { "未实现的算子: ${op.name}" }
                "torch.zeros(1)  # Unsupported op: ${op.name}"
            }
        }

        // 处理输出
        if (node.outputs.size == 1) {
            val outputVar = node.outputs[0].valueId
            builder.appendLine("        $outputVar = $call")
            valueMap[outputVar] = outputVar
        } else {
            // 多输出（如 SPLIT）
            val outputVars = node.outputs.map { it.valueId }
            if (outputVars.isNotEmpty()) {
                builder.appendLine("        ${outputVars.joinToString(", ")} = $call")
                outputVars.forEach { valueMap[it] = it }
            }
        }
    }

    /**
     * 将 UirShape 转换为 Python 列表字符串。
     */
    private fun shapeToPython(shape: UirShape): String {
        return shape.dims.map { dim ->
            when (dim.dimKind) {
                UirDimKind.CONSTANT -> dim.value?.toString() ?: "1"
                UirDimKind.SYMBOLIC -> "1"  // 符号维度用 1 代替
                UirDimKind.UNKNOWN -> "1"
            }
        }.joinToString(", ")
    }
}
