package io.github.xyzboom.aiFuzzer.translator.tvm

import io.github.xyzboom.aiFuzzer.ir.*
import io.github.xyzboom.aiFuzzer.ir.types.*
import io.github.xyzboom.aiFuzzer.ir.visitors.UirVisitorVoid
import io.github.xyzboom.aiFuzzer.translator.UirTranslator

/**
 * UIR 到 TVM Relax Python 代码的翻译器。
 *
 * 设计原则：
 * 1. 直接读取 ValueRef.type.shape，不再维护独立的 ndimMap
 * 2. 形状推导由 ShapeInferer 统一完成，翻译器只负责代码生成
 * 3. 不需要 clamp axis，因为生成器已保证语义合法
 *
 * @param shapeRank 默认形状秩（用于生成默认 shape）
 * @param dtype 默认数据类型
 */
class TvmRelaxTranslator(
    private val shapeRank: Int = 16,
    private val dtype: String = "float32"
) : UirTranslator<UirProgram, String> {
    
    /**
     * 将 UIR 程序翻译为 TVM Relax Python 代码。
     */
    override fun translate(program: UirProgram): String {
        val builder = StringBuilder()
        
        // 生成 Python 模板
        builder.appendLine("# Auto-generated by aiFuzzer")
        builder.appendLine()
        builder.appendLine("import tvm")
        builder.appendLine("from tvm import relax")
        builder.appendLine("from tvm.ir.module import IRModule")
        builder.appendLine("import numpy as np")
        builder.appendLine()
        builder.appendLine("def build_mod():")
        builder.appendLine("    bb = relax.BlockBuilder()")
        builder.appendLine()
        
        // 翻译每个图
        for ((idx, graph) in program.graphs.withIndex()) {
            translateGraph(builder, graph, idx)
        }
        
        builder.appendLine("    mod = bb.get()")
        builder.appendLine("    return mod")
        builder.appendLine()
        builder.appendLine()
        builder.appendLine("if __name__ == '__main__':")
        builder.appendLine("    mod = build_mod()")
        builder.appendLine("    print('Module built successfully')")
        builder.appendLine("    # print(mod)")
        
        return builder.toString()
    }
    
    /**
     * 翻译单个计算图。
     */
    private fun translateGraph(builder: StringBuilder, graph: UirGraph, graphIdx: Int) {
        val funcName = graph.name.ifBlank { "func_$graphIdx" }
        
        // 创建函数输入变量
        val inputVars = mutableListOf<String>()
        for ((i, input) in graph.inputs.withIndex()) {
            val varName = "${input.valueId}_var"
            inputVars.add(varName)
            val shapeExpr = generateShapeExpr(input.type.shape)
            builder.appendLine("    ${varName}_param = relax.Var(\"${input.valueId}\", relax.TensorType($shapeExpr, \"$dtype\"))")
        }
        
        // 开始函数定义
        val params = inputVars.mapIndexed { i, v -> "${graph.inputs[i].valueId}_var" }.joinToString(", ")
        builder.appendLine("    with bb.function(\"$funcName\", [${graph.inputs.map { "${it.valueId}_var" }.joinToString(", ")}]):")
        
        // 生成输入变量的 relax.Var
        for (input in graph.inputs) {
            val varName = "${input.valueId}_var"
            val shapeExpr = generateShapeExpr(input.type.shape)
            builder.appendLine("        $varName = relax.Var(\"${input.valueId}\", relax.TensorType($shapeExpr, \"$dtype\"))")
        }
        
        // 值映射：valueId -> Python 变量名
        val valueMap = mutableMapOf<String, String>()
        
        // 图输入映射
        for (input in graph.inputs) {
            valueMap[input.valueId] = "${input.valueId}_var"
        }
        
        // 翻译每个节点
        for (node in graph.nodes) {
            translateNode(builder, node, valueMap)
        }
        
        // 生成函数输出
        val outputVars = graph.outputs.map { output ->
            valueMap[output.valueId] ?: "${output.valueId}_var"
        }
        
        if (outputVars.size == 1) {
            builder.appendLine("        bb.emit_func_output(${outputVars[0]})")
        } else {
            builder.appendLine("        bb.emit_func_output((${outputVars.joinToString(", ")}))")
        }
        
        builder.appendLine()
    }
    
    /**
     * 翻译单个节点。
     */
    private fun translateNode(builder: StringBuilder, node: UirNode, valueMap: MutableMap<String, String>) {
        // 获取输入变量
        val inputVars = node.inputs.map { input ->
            valueMap[input.valueId] ?: "${input.valueId}_var"
        }
        
        // 生成 TVM Relax 调用
        val relaxCall = generateRelaxCall(node.op, inputVars, node.attributes)
        
        // 处理输出
        if (node.outputs.size == 1) {
            val outputVar = node.outputs[0].valueId
            builder.appendLine("        $outputVar = bb.emit($relaxCall)")
            valueMap[outputVar] = outputVar
        } else {
            // 多输出
            val outputVars = node.outputs.map { it.valueId }
            builder.appendLine("        ${outputVars.joinToString(", ")} = bb.emit($relaxCall)")
            outputVars.forEach { valueMap[it] = it }
        }
    }
    
    /**
     * 生成 TVM Relax 算子调用。
     */
    private fun generateRelaxCall(
        op: UirOpKind,
        inputVars: List<String>,
        attributes: Map<String, Attribute>
    ): String {
        return when (op) {
            // ===== 一元激活 =====
            UirOpKind.RELU -> "relax.op.nn.relu(${inputVars[0]})"
            UirOpKind.SIGMOID -> "relax.op.sigmoid(${inputVars[0]})"
            UirOpKind.TANH -> "relax.op.tanh(${inputVars[0]})"
            UirOpKind.GELU -> "relax.op.nn.gelu(${inputVars[0]})"
            UirOpKind.SILU -> "relax.op.nn.silu(${inputVars[0]})"
            
            // ===== 一元数学 =====
            UirOpKind.NEG -> "relax.op.negative(${inputVars[0]})"
            UirOpKind.ABS -> "relax.op.abs(${inputVars[0]})"
            UirOpKind.EXP -> "relax.op.exp(${inputVars[0]})"
            UirOpKind.LOG -> "relax.op.log(${inputVars[0]})"
            UirOpKind.SQRT -> "relax.op.sqrt(${inputVars[0]})"
            UirOpKind.CEIL -> "relax.op.ceil(${inputVars[0]})"
            UirOpKind.FLOOR -> "relax.op.floor(${inputVars[0]})"
            
            // ===== 二元运算 =====
            UirOpKind.ADD -> "relax.op.add(${inputVars[0]}, ${inputVars[1]})"
            UirOpKind.SUBTRACT -> "relax.op.subtract(${inputVars[0]}, ${inputVars[1]})"
            UirOpKind.MULTIPLY -> "relax.op.multiply(${inputVars[0]}, ${inputVars[1]})"
            UirOpKind.DIVIDE -> "relax.op.divide(${inputVars[0]}, ${inputVars[1]})"
            UirOpKind.MAXIMUM -> "relax.op.maximum(${inputVars[0]}, ${inputVars[1]})"
            UirOpKind.MINIMUM -> "relax.op.minimum(${inputVars[0]}, ${inputVars[1]})"
            UirOpKind.POWER -> "relax.op.power(${inputVars[0]}, ${inputVars[1]})"
            
            // ===== 矩阵乘法 =====
            UirOpKind.MATMUL -> "relax.op.matmul(${inputVars[0]}, ${inputVars[1]})"
            
            // ===== SOFTMAX =====
            UirOpKind.SOFTMAX -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                "relax.op.nn.softmax(${inputVars[0]}, axis=$axis)"
            }
            
            // ===== 归约 =====
            UirOpKind.REDUCE_SUM -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.sum(${inputVars[0]}, axis=[$axis], keepdims=$keepdims)"
            }
            UirOpKind.REDUCE_MEAN -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.mean(${inputVars[0]}, axis=[$axis], keepdims=$keepdims)"
            }
            UirOpKind.REDUCE_MAX -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.max(${inputVars[0]}, axis=[$axis], keepdims=$keepdims)"
            }
            UirOpKind.REDUCE_MIN -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.min(${inputVars[0]}, axis=[$axis], keepdims=$keepdims)"
            }
            
            // ===== 形状变换 =====
            UirOpKind.RESHAPE -> {
                // 从输入形状推断目标形状
                val ndim = inputVars.size  // 简化处理，实际应从属性读取
                "relax.op.reshape(${inputVars[0]}, relax.ShapeExpr([-1]))"
            }
            UirOpKind.TRANSPOSE -> {
                "relax.op.permute_dims(${inputVars[0]})"
            }
            UirOpKind.SQUEEZE -> {
                "relax.op.squeeze(${inputVars[0]})"
            }
            UirOpKind.UNSQUEEZE -> {
                "relax.op.expand_dims(${inputVars[0]}, axis=0)"
            }
            
            // ===== 拼接/分割 =====
            UirOpKind.CONCAT -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.concat([${inputVars.joinToString(", ")}], axis=$axis)"
            }
            UirOpKind.SPLIT -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.split(${inputVars[0]}, 2, axis=$axis)"
            }
            
            // ===== 索引 =====
            UirOpKind.GATHER -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.take(${inputVars[0]}, relax.const(0, dtype=\"int64\"), axis=$axis)"
            }
            UirOpKind.STRIDED_SLICE -> {
                "relax.op.strided_slice(${inputVars[0]}, axes=[0], begin=[0], end=[-1])"
            }
            
            // ===== 三角矩阵 =====
            UirOpKind.TRIL -> "relax.op.tril(${inputVars[0]})"
            UirOpKind.TRIU -> "relax.op.triu(${inputVars[0]})"
            
            // ===== 广播/填充 =====
            UirOpKind.BROADCAST_TO -> {
                "relax.op.broadcast_to(${inputVars[0]}, relax.ShapeExpr([$shapeRank]))"
            }
            UirOpKind.TILE -> {
                "relax.op.tile(${inputVars[0]}, [1])"
            }
            
            // ===== 类型转换 =====
            UirOpKind.CAST -> {
                "relax.op.astype(${inputVars[0]}, dtype=\"$dtype\")"
            }
            
            // ===== 常数生成 =====
            UirOpKind.ARANGE -> {
                "relax.op.arange(0, $shapeRank, dtype=\"$dtype\")"
            }
            UirOpKind.FULL -> {
                "relax.op.full(relax.ShapeExpr([$shapeRank]), fill_value=0, dtype=\"$dtype\")"
            }
            UirOpKind.ONES -> {
                "relax.op.ones(relax.ShapeExpr([$shapeRank]), dtype=\"$dtype\")"
            }
            UirOpKind.ZEROS -> {
                "relax.op.zeros(relax.ShapeExpr([$shapeRank]), dtype=\"$dtype\")"
            }
            
            // ===== 适配算子 =====
            UirOpKind.EXPAND_DIMS -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.expand_dims(${inputVars[0]}, axis=$axis)"
            }
        }
    }
    
    /**
     * 生成 ShapeExpr 字符串。
     */
    private fun generateShapeExpr(shape: UirShape): String {
        if (shape.dims.isEmpty()) {
            return "relax.ShapeExpr([])"
        }
        
        val dims = shape.dims.map { dim ->
            when (dim.dimKind) {
                UirDimKind.CONSTANT -> dim.value?.toString() ?: shapeRank.toString()
                UirDimKind.SYMBOLIC -> shapeRank.toString()  // 符号维度暂时用固定值
                UirDimKind.UNKNOWN -> shapeRank.toString()    // 未知维度暂时用固定值
            }
        }
        
        return "relax.ShapeExpr([${dims.joinToString(", ")}])"
    }
}