package io.github.xyzboom.aiFuzzer.translator.tvm

import io.github.oshai.kotlinlogging.KotlinLogging
import io.github.xyzboom.aiFuzzer.ir.*
import io.github.xyzboom.aiFuzzer.ir.types.*
import io.github.xyzboom.aiFuzzer.translator.UirTranslator

private val log = KotlinLogging.logger {}

/**
 * UIR 到 TVM Relax Python 代码的翻译器。
 *
 * 设计原则：
 * 1. 直接读取 ValueRef.type.shape，不再维护独立的 ndimMap
 * 2. 形状推导由 ShapeInferer 统一完成，翻译器只负责代码生成
 * 3. 不需要 clamp axis，因为生成器已保证语义合法
 *
 * @param shapeRank 默认形状秩（用于生成默认 shape，当形状未知时使用）
 * @param dtype 默认数据类型
 * @param opNameMapping 自定义算子名映射（可选）
 * @param dtypeMapping 自定义数据类型映射（可选）
 */
class TvmRelaxTranslator(
    private val shapeRank: Int = 16,
    private val dtype: String = "float32",
    private val opNameMapping: Map<UirOpKind, String> = defaultOpNameMapping,
    private val dtypeMapping: Map<String, String> = emptyMap()
) : UirTranslator<UirProgram, String> {

    companion object {
        /**
         * 默认算子名映射：UIR 算子 -> TVM Relax 算子路径。
         */
        val defaultOpNameMapping: Map<UirOpKind, String> = mapOf(
            // 一元激活
            UirOpKind.RELU to "relax.op.nn.relu",
            UirOpKind.SIGMOID to "relax.op.sigmoid",
            UirOpKind.TANH to "relax.op.tanh",
            UirOpKind.GELU to "relax.op.nn.gelu",
            UirOpKind.SILU to "relax.op.nn.silu",

            // 一元数学
            UirOpKind.NEG to "relax.op.negative",
            UirOpKind.ABS to "relax.op.abs",
            UirOpKind.EXP to "relax.op.exp",
            UirOpKind.LOG to "relax.op.log",
            UirOpKind.SQRT to "relax.op.sqrt",
            UirOpKind.CEIL to "relax.op.ceil",
            UirOpKind.FLOOR to "relax.op.floor",

            // 二元运算
            UirOpKind.ADD to "relax.op.add",
            UirOpKind.SUBTRACT to "relax.op.subtract",
            UirOpKind.MULTIPLY to "relax.op.multiply",
            UirOpKind.DIVIDE to "relax.op.divide",
            UirOpKind.MAXIMUM to "relax.op.maximum",
            UirOpKind.MINIMUM to "relax.op.minimum",
            UirOpKind.POWER to "relax.op.power",

            // 矩阵乘法
            UirOpKind.MATMUL to "relax.op.matmul",

            // 卷积
            UirOpKind.CONV2D to "relax.op.nn.conv2d",
            UirOpKind.MAX_POOL2D to "relax.op.nn.max_pool2d",
            UirOpKind.AVG_POOL2D to "relax.op.nn.avg_pool2d",

            // 归一化
            UirOpKind.LAYER_NORM to "relax.op.nn.layer_norm",
            UirOpKind.BATCH_NORM to "relax.op.nn.batch_norm",

            // SOFTMAX
            UirOpKind.SOFTMAX to "relax.op.nn.softmax",

            // 归约
            UirOpKind.REDUCE_SUM to "relax.op.sum",
            UirOpKind.REDUCE_MEAN to "relax.op.mean",
            UirOpKind.REDUCE_MAX to "relax.op.max",
            UirOpKind.REDUCE_MIN to "relax.op.min",

            // 形状变换
            UirOpKind.RESHAPE to "relax.op.reshape",
            UirOpKind.TRANSPOSE to "relax.op.permute_dims",
            UirOpKind.SQUEEZE to "relax.op.squeeze",
            UirOpKind.UNSQUEEZE to "relax.op.expand_dims",

            // 拼接/分割
            UirOpKind.CONCAT to "relax.op.concat",
            UirOpKind.SPLIT to "relax.op.split",

            // 索引
            UirOpKind.GATHER to "relax.op.take",
            UirOpKind.STRIDED_SLICE to "relax.op.strided_slice",

            // 三角矩阵
            UirOpKind.TRIL to "relax.op.tril",
            UirOpKind.TRIU to "relax.op.triu",

            // 广播/填充
            UirOpKind.BROADCAST_TO to "relax.op.broadcast_to",
            UirOpKind.TILE to "relax.op.tile",

            // 类型转换
            UirOpKind.CAST to "relax.op.astype",

            // 常数生成
            UirOpKind.ARANGE to "relax.op.arange",
            UirOpKind.FULL to "relax.op.full",
            UirOpKind.ONES to "relax.op.ones",
            UirOpKind.ZEROS to "relax.op.zeros",

            // 适配算子
            UirOpKind.EXPAND_DIMS to "relax.op.expand_dims"
        )
    }

    /**
     * 将 UIR 程序翻译为 TVM Relax Python 代码。
     */
    override fun translate(element: UirProgram): String {
        log.debug { "开始翻译 UIR 程序: ${element.graphs.size} 个图" }
        val startTime = System.currentTimeMillis()
        val builder = StringBuilder()

        // 生成 Python 模板
        builder.appendLine("# Auto-generated by aiFuzzer")
        builder.appendLine()
        builder.appendLine("import tvm")
        builder.appendLine("from tvm import relax")
        builder.appendLine("from tvm.ir.module import IRModule")
        builder.appendLine("import numpy as np")
        builder.appendLine()
        builder.appendLine("def build_mod():")
        builder.appendLine("    bb = relax.BlockBuilder()")
        builder.appendLine()

        // 翻译每个图
        for ((idx, graph) in element.graphs.withIndex()) {
            log.trace { "翻译图 $idx: ${graph.name}" }
            translateGraph(builder, graph, idx)
        }

        builder.appendLine("    mod = bb.get()")
        builder.appendLine("    return mod")
        builder.appendLine()
        builder.appendLine()
        // IMPORTANT: we should not use __name__ == "__main__" guard here, because the daemon will execute this script directly.
        builder.appendLine("mod = build_mod()")
        builder.appendLine("print('Module built successfully')")
        builder.appendLine("# print(mod)")

        val elapsed = System.currentTimeMillis() - startTime
        log.debug { "翻译完成，耗时 ${elapsed}ms，输出 ${builder.length} 字符" }
        return builder.toString()
    }

    /**
     * 翻译单个计算图。
     */
    private fun translateGraph(builder: StringBuilder, graph: UirGraph, graphIdx: Int) {
        val funcName = graph.name.ifBlank { "func_$graphIdx" }

        // 生成输入变量的 relax.Var
        for (input in graph.inputs) {
            val varName = "${input.valueId}_var"
            val shapeExpr = generateShapeExpr(input.type.shape)
            builder.appendLine("    $varName = relax.Var(\"${input.valueId}\", relax.TensorStructInfo(shape=$shapeExpr, dtype=\"$dtype\"))")
        }

        // 开始函数定义
        val params = graph.inputs.map { "${it.valueId}_var" }.joinToString(", ")
        builder.appendLine("    with bb.function(\"$funcName\", [$params]):")

        // 值映射：valueId -> Python 变量名
        val valueMap = mutableMapOf<String, String>()

        // 图输入映射
        for (input in graph.inputs) {
            valueMap[input.valueId] = "${input.valueId}_var"
        }

        // 翻译每个节点
        for (node in graph.nodes) {
            translateNode(builder, node, valueMap)
        }

        // 生成函数输出
        val outputVars = graph.outputs.map { output ->
            valueMap[output.valueId] ?: "${output.valueId}_var"
        }

        if (outputVars.size == 1) {
            builder.appendLine("        bb.emit_func_output(${outputVars[0]})")
        } else {
            builder.appendLine("        bb.emit_func_output((${outputVars.joinToString(", ")}))")
        }

        builder.appendLine()
    }

    /**
     * 翻译单个节点。
     */
    private fun translateNode(builder: StringBuilder, node: UirNode, valueMap: MutableMap<String, String>) {
        // 获取输入变量
        val inputVars = node.inputs.map { input ->
            valueMap[input.valueId] ?: "${input.valueId}_var"
        }

        // 生成 TVM Relax 调用
        val relaxCall = generateRelaxCall(node.op, inputVars, node.attributes, node.inputs.map { it.type.shape }, node.outputs.map { it.type.shape })

        builder.appendLine("        # input: ${node.inputs.map { it.type.shape }.joinToString { it.rawShapeString() }}")
        builder.appendLine("        # output: ${node.outputs.map { it.type.shape }.joinToString { it.rawShapeString() }}")

        // 处理输出
        if (node.outputs.size == 1) {
            val outputVar = node.outputs[0].valueId
            builder.appendLine("        $outputVar = bb.emit($relaxCall)")
            valueMap[outputVar] = outputVar
            
            // 添加形状断言
            val expectedShape = node.outputs[0].type.shape
            addShapeAssertion(builder, outputVar, expectedShape)
        } else {
            // 多输出
            val outputVars = node.outputs.map { it.valueId }
            builder.appendLine("        ${outputVars.joinToString(", ")} = bb.emit($relaxCall)")
            outputVars.forEach { valueMap[it] = it }
            
            // 为每个输出添加形状断言
            for (i in node.outputs.indices) {
                val outputVar = outputVars[i]
                val expectedShape = node.outputs[i].type.shape
                addShapeAssertion(builder, outputVar, expectedShape)
            }
        }
    }

    /**
     * 生成 TVM Relax 算子调用。
     */
    private fun generateRelaxCall(
        op: UirOpKind,
        inputVars: List<String>,
        attributes: Map<String, Attribute>,
        inputShapes: List<UirShape>,
        outputShapes: List<UirShape>
    ): String {
        return when (op) {
            // ===== 一元激活 =====
            UirOpKind.RELU -> "relax.op.nn.relu(${inputVars[0]})"
            UirOpKind.SIGMOID -> "relax.op.sigmoid(${inputVars[0]})"
            UirOpKind.TANH -> "relax.op.tanh(${inputVars[0]})"
            UirOpKind.GELU -> "relax.op.nn.gelu(${inputVars[0]})"
            UirOpKind.SILU -> "relax.op.nn.silu(${inputVars[0]})"

            // ===== 一元数学 =====
            UirOpKind.NEG -> "relax.op.negative(${inputVars[0]})"
            UirOpKind.ABS -> "relax.op.abs(${inputVars[0]})"
            UirOpKind.EXP -> "relax.op.exp(${inputVars[0]})"
            UirOpKind.LOG -> "relax.op.log(${inputVars[0]})"
            UirOpKind.SQRT -> "relax.op.sqrt(${inputVars[0]})"
            UirOpKind.CEIL -> "relax.op.ceil(${inputVars[0]})"
            UirOpKind.FLOOR -> "relax.op.floor(${inputVars[0]})"

            // ===== 二元运算 =====
            UirOpKind.ADD -> "relax.op.add(${inputVars[0]}, ${inputVars.getOrElse(1) { inputVars[0] }})"
            UirOpKind.SUBTRACT -> "relax.op.subtract(${inputVars[0]}, ${inputVars.getOrElse(1) { inputVars[0] }})"
            UirOpKind.MULTIPLY -> "relax.op.multiply(${inputVars[0]}, ${inputVars.getOrElse(1) { inputVars[0] }})"
            UirOpKind.DIVIDE -> "relax.op.divide(${inputVars[0]}, ${inputVars.getOrElse(1) { inputVars[0] }})"
            UirOpKind.MAXIMUM -> "relax.op.maximum(${inputVars[0]}, ${inputVars.getOrElse(1) { inputVars[0] }})"
            UirOpKind.MINIMUM -> "relax.op.minimum(${inputVars[0]}, ${inputVars.getOrElse(1) { inputVars[0] }})"
            UirOpKind.POWER -> "relax.op.power(${inputVars[0]}, ${inputVars.getOrElse(1) { inputVars[0] }})"

            // ===== 矩阵乘法 =====
            UirOpKind.MATMUL -> {
                // 为了避免形状不兼容，使用 full 替换（类似旧实现）
                // 当输入形状已知且为 2-D 时，直接调用 matmul
                // 否则使用固定的 full 替换
                "relax.op.matmul(${inputVars[0]}, ${inputVars[1]})"
            }

            // ===== 卷积 =====
            UirOpKind.CONV2D -> {
                val stride = (attributes["stride"] as? UirIntAttr)?.value ?: 1
                val padding = (attributes["padding"] as? UirIntAttr)?.value ?: 0
                val dilation = (attributes["dilation"] as? UirIntAttr)?.value ?: 1
                val groups = (attributes["groups"] as? UirIntAttr)?.value ?: 1
                "relax.op.nn.conv2d(${inputVars[0]}, ${inputVars[1]}, " +
                    "strides=[$stride, $stride], " +
                    "padding=[$padding, $padding], " +
                    "dilation=[$dilation, $dilation], " +
                    "groups=$groups)"
            }

            // ===== 池化 =====
            UirOpKind.MAX_POOL2D -> {
                val kernelSize = (attributes["kernel_size"] as? UirIntAttr)?.value ?: 2
                val stride = (attributes["stride"] as? UirIntAttr)?.value ?: kernelSize
                val padding = (attributes["padding"] as? UirIntAttr)?.value ?: 0
                "relax.op.nn.max_pool2d(${inputVars[0]}, " +
                    "pool_size=[$kernelSize, $kernelSize], " +
                    "strides=[$stride, $stride], " +
                    "padding=[$padding, $padding])"
            }
            UirOpKind.AVG_POOL2D -> {
                val kernelSize = (attributes["kernel_size"] as? UirIntAttr)?.value ?: 2
                val stride = (attributes["stride"] as? UirIntAttr)?.value ?: kernelSize
                val padding = (attributes["padding"] as? UirIntAttr)?.value ?: 0
                "relax.op.nn.avg_pool2d(${inputVars[0]}, " +
                    "pool_size=[$kernelSize, $kernelSize], " +
                    "strides=[$stride, $stride], " +
                    "padding=[$padding, $padding])"
            }

            // ===== 归一化 =====
            UirOpKind.LAYER_NORM -> {
                // LayerNorm: 对最后一个维度归一化
                "relax.op.nn.layer_norm(${inputVars[0]})"
            }
            UirOpKind.BATCH_NORM -> {
                // BatchNorm: 需要运行统计信息，这里简化处理
                "relax.op.nn.batch_norm(${inputVars[0]})"
            }

            // ===== SOFTMAX =====
            UirOpKind.SOFTMAX -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                "relax.op.nn.softmax(${inputVars[0]}, axis=$axis)"
            }

            // ===== 归约 =====
            UirOpKind.REDUCE_SUM -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.sum(${inputVars[0]}, axis=[$axis], keepdims=${
                    keepdims.toString().replaceFirstChar { it.uppercase() }
                })"
            }

            UirOpKind.REDUCE_MEAN -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.mean(${inputVars[0]}, axis=[$axis], keepdims=${
                    keepdims.toString().replaceFirstChar { it.uppercase() }
                })"
            }

            UirOpKind.REDUCE_MAX -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.max(${inputVars[0]}, axis=[$axis], keepdims=${
                    keepdims.toString().replaceFirstChar { it.uppercase() }
                })"
            }

            UirOpKind.REDUCE_MIN -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: -1
                val keepdims = (attributes["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                "relax.op.min(${inputVars[0]}, axis=[$axis], keepdims=${
                    keepdims.toString().replaceFirstChar { it.uppercase() }
                })"
            }

            // ===== 形状变换 =====
            UirOpKind.RESHAPE -> {
                "relax.op.reshape(${inputVars[0]}, relax.ShapeExpr([-1]))"
            }

            UirOpKind.TRANSPOSE -> {
                "relax.op.permute_dims(${inputVars[0]})"
            }

            UirOpKind.SQUEEZE -> {
                "relax.op.squeeze(${inputVars[0]})"
            }

            UirOpKind.UNSQUEEZE -> {
                "relax.op.expand_dims(${inputVars[0]}, axis=0)"
            }

            // ===== 拼接/分割 =====
            UirOpKind.CONCAT -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.concat([${inputVars.joinToString(", ")}], axis=$axis)"
            }

            UirOpKind.SPLIT -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.split(${inputVars[0]}, 2, axis=$axis)"
            }

            // ===== 索引 =====
            UirOpKind.GATHER -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.take(${inputVars[0]}, relax.const(0, dtype=\"int64\"), axis=$axis)"
            }

            UirOpKind.STRIDED_SLICE -> {
                "relax.op.strided_slice(${inputVars[0]}, axes=[0], begin=[0], end=[-1])"
            }

            // ===== 三角矩阵 =====
            UirOpKind.TRIL -> "relax.op.tril(${inputVars[0]})"
            UirOpKind.TRIU -> "relax.op.triu(${inputVars[0]})"

            // ===== 广播/填充 =====
            UirOpKind.BROADCAST_TO -> {
                // 从节点输出读取目标形状
                val targetShape = outputShapes[0]
                val shapeStr = targetShape.dims.map { dim ->
                    when (dim.dimKind) {
                        UirDimKind.CONSTANT -> dim.value.toString()
                        else -> shapeRank.toString()  // 未知维度用默认值
                    }
                }.joinToString(", ")
                "relax.op.broadcast_to(${inputVars[0]}, relax.ShapeExpr([$shapeStr]))"
            }

            UirOpKind.TILE -> {
                "relax.op.tile(${inputVars[0]}, [1])"
            }

            // ===== 类型转换 =====
            UirOpKind.CAST -> {
                "relax.op.astype(${inputVars[0]}, dtype=\"$dtype\")"
            }

            // ===== 常数生成 =====
            UirOpKind.ARANGE -> {
                // 计算输出张量的总元素数量
                val targetShape = outputShapes[0]
                val totalSize = targetShape.dims.fold(1) { acc, dim ->
                    acc * (if (dim.dimKind == UirDimKind.CONSTANT) dim.value ?: 1 else 1)
                }
                "relax.op.arange(0, $totalSize, dtype=\"$dtype\")"
            }

            UirOpKind.FULL -> {
                val targetShape = outputShapes[0]
                val shapeStr = targetShape.dims.map { dim ->
                    when (dim.dimKind) {
                        UirDimKind.CONSTANT -> dim.value.toString()
                        else -> shapeRank.toString()  // 未知维度用默认值
                    }
                }.joinToString(", ")
                "relax.op.full(relax.ShapeExpr([$shapeStr]), relax.const(0, dtype=\"$dtype\"))"
            }

            UirOpKind.ONES -> {
                val targetShape = outputShapes[0]
                val shapeStr = targetShape.dims.map { dim ->
                    when (dim.dimKind) {
                        UirDimKind.CONSTANT -> dim.value.toString()
                        else -> shapeRank.toString()  // 未知维度用默认值
                    }
                }.joinToString(", ")
                "relax.op.ones(relax.ShapeExpr([$shapeStr]), dtype=\"$dtype\")"
            }

            UirOpKind.ZEROS -> {
                val targetShape = outputShapes[0]
                val shapeStr = targetShape.dims.map { dim ->
                    when (dim.dimKind) {
                        UirDimKind.CONSTANT -> dim.value.toString()
                        else -> shapeRank.toString()  // 未知维度用默认值
                    }
                }.joinToString(", ")
                "relax.op.zeros(relax.ShapeExpr([$shapeStr]), dtype=\"$dtype\")"
            }

            // ===== 适配算子 =====
            UirOpKind.EXPAND_DIMS -> {
                val axis = (attributes["axis"] as? UirIntAttr)?.value ?: 0
                "relax.op.expand_dims(${inputVars[0]}, axis=$axis)"
            }
        }
    }

    /**
     * 添加形状断言。
     * 断言输出的实际形状与推断的形状一致。
     */
    private fun addShapeAssertion(builder: StringBuilder, outputVar: String, expectedShape: UirShape) {
        // 生成期望形状的字符串表示
        val expectedShapeStr = generateShapeAssertionExpr(expectedShape)
        
        // 使用 relax 的结构信息检查
        builder.appendLine("        assert str($outputVar.struct_info.shape) == \"$expectedShapeStr\", f\"Shape mismatch: expected $expectedShapeStr, got {$outputVar.struct_info.shape}\"")
    }

    /**
     * 生成用于断言的形状表达式字符串。
     */
    private fun generateShapeAssertionExpr(shape: UirShape): String {
        if (shape.dims.isEmpty()) {
            return "R.shape([])"
        }

        val dims = shape.dims.map { dim ->
            when (dim.dimKind) {
                UirDimKind.CONSTANT -> dim.value?.toString() ?: shapeRank.toString()
                UirDimKind.SYMBOLIC -> shapeRank.toString()  // 符号维度暂时用固定值
                UirDimKind.UNKNOWN -> shapeRank.toString()    // 未知维度暂时用固定值
            }
        }

        return "R.shape([${dims.joinToString(", ")}])"
    }

    /**
     * 生成 ShapeExpr 字符串。
     */
    private fun generateShapeExpr(shape: UirShape): String {
        if (shape.dims.isEmpty()) {
            return "relax.ShapeExpr([])"
        }

        return "relax.ShapeExpr(${shape.rawShapeString()})"
    }

    private fun UirShape.rawShapeString(): String {
        val dims = dims.map { dim ->
            when (dim.dimKind) {
                UirDimKind.CONSTANT -> dim.value?.toString() ?: shapeRank.toString()
                UirDimKind.SYMBOLIC -> shapeRank.toString()  // 符号维度暂时用固定值
                UirDimKind.UNKNOWN -> shapeRank.toString()    // 未知维度暂时用固定值
            }
        }

        return "[${dims.joinToString(", ")}]"
    }
}