package io.github.xyzboom.aiFuzzer.translator.onnx

import io.github.oshai.kotlinlogging.KotlinLogging
import io.github.xyzboom.aiFuzzer.ir.*
import io.github.xyzboom.aiFuzzer.ir.types.*
import io.github.xyzboom.aiFuzzer.translator.UirTranslator

private val log = KotlinLogging.logger {}

class OnnxTranslator(
    private val opsetVersion: Int = 11,
    private val irVersion: Int = 8,
) : UirTranslator<UirProgram, String> {

    companion object {
        private val dtypeMap = mapOf(
            "float32" to "TensorProto.FLOAT",
            "float16" to "TensorProto.FLOAT16",
            "float64" to "TensorProto.DOUBLE",
            "int32" to "TensorProto.INT32",
            "int64" to "TensorProto.INT64",
            "bool" to "TensorProto.BOOL",
            "uint8" to "TensorProto.UINT8",
        )
        private fun toOnnxDtype(irDtype: String): String = dtypeMap[irDtype] ?: "TensorProto.FLOAT"
        private const val FLOAT = "TensorProto.FLOAT"
        private const val INT64 = "TensorProto.INT64"
    }

    override fun translate(element: UirProgram): String {
        log.debug { "开始翻译 ONNX 程序: ${element.graphs.size} 个图" }
        val startTime = System.currentTimeMillis()
        val builder = StringBuilder()

        builder.appendLine("# Auto-generated by aiFuzzer - ONNX")
        builder.appendLine()
        builder.appendLine("from onnx import helper, TensorProto")
        builder.appendLine("import onnxruntime as ort")
        builder.appendLine("import numpy as np")
        builder.appendLine()

        for ((idx, graph) in element.graphs.withIndex()) {
            translateGraph(builder, graph, idx)
        }

        builder.appendLine("print('Execution: OK')")

        val elapsed = System.currentTimeMillis() - startTime
        log.debug { "翻译完成，耗时 ${elapsed}ms，输出 ${builder.length} 字符" }
        return builder.toString()
    }

    /** 追踪每个 make_node 调用的变量名，用于 make_graph 的 node list */
    private data class NodeLine(val varName: String, val code: String)

    // Ops that are compound (multiple ONNX nodes unioned together)
    @Suppress("EnumValuesSoftDeprecate")
    private val compoundOpsSet = setOf(
        UirOpKind.GELU, UirOpKind.SILU, UirOpKind.MISH,
        UirOpKind.RSQRT, UirOpKind.LOG2,
        UirOpKind.ARGMAX, UirOpKind.ARGMIN,
    )

    // Ops where opset 11+ requires parameters as constant inputs, not attributes
    @Suppress("EnumValuesSoftDeprecate")
    private val inputParamOps = setOf(
        UirOpKind.CLAMP, UirOpKind.HARDTANH,
    )

    /** Generate a unique node variable name */
    private var nodeCounter = 0L
    private fun nextNodeVar(): String { nodeCounter++; return "n$nodeCounter" }

    // ────────────────────────────────────────────────────────────────
    // Graph translation
    // ────────────────────────────────────────────────────────────────
    private fun translateGraph(builder: StringBuilder, graph: UirGraph, graphIdx: Int) {
        val funcName = graph.name.ifBlank { "graph_$graphIdx" }
        val allNodes = graph.nodes.toList()
        val tensorInitLines = mutableListOf<String>()   // make_tensor calls
        val valueDtypeMap = mutableMapOf<String, String>()
        val nodeLines = mutableListOf<NodeLine>()
        val outputTensors = mutableListOf<String>()

        for (input in graph.inputs) {
            valueDtypeMap[input.valueId] = toOnnxDtype(input.type.dtype.name)
        }

        for (node in allNodes) {
            val inputIds = node.inputs.map { it.valueId }
            val outputIds = node.outputs.map { it.valueId }
            val outputId = outputIds.first()
            val inputId = inputIds.firstOrNull()
            val onnxOp = opToOnnx(node.op)

            // ─── 1. Compound operations (multiple ONNX nodes) ─────
            if (onnxOp == null && node.op in compoundOpsSet) {
                translateCompoundOp(node, outputId, inputId, tensorInitLines, nodeLines, valueDtypeMap)
                continue
            }

            // ─── 2. Unsupported → zeros tensor fallback ────────────
            if (onnxOp == null && node.op !in inputParamOps) {
                for (outId in outputIds) {
                    val shape = node.outputs.find { it.valueId == outId }?.type?.shape
                    val shapeStr = shape?.let { shapeToPythonList(it) } ?: "[]"
                    val numel = shape?.dims?.fold(1L) { a, d -> a * ((d.value ?: 1).toLong()) } ?: 1L
                    val fill = if (numel > 1) "[0.0] * $numel" else "[0.0]"
                    tensorInitLines.add("""${outId}_t = helper.make_tensor("${outId}_v", TensorProto.FLOAT, $shapeStr, $fill)""")
                    val nv = nextNodeVar()
                    nodeLines.add(NodeLine(nv, "    $nv = helper.make_node('Constant', inputs=[], outputs=['$outId'], value=${outId}_t)"))
                }
                continue
            }

            // ─── 3. Constant ops (FULL, ZEROS, ONES, ARANGE) ──────
            if (node.op in setOf(UirOpKind.FULL, UirOpKind.ZEROS, UirOpKind.ONES, UirOpKind.ARANGE)) {
                val shape = node.outputs[0].type.shape
                val dtype = node.outputs[0].type.dtype.name
                val onnxDtype = toOnnxDtype(dtype)
                valueDtypeMap[outputId] = onnxDtype
                val shapeStr = shapeToPythonList(shape)

                val numel = shape.dims.fold(1L) { a, d -> a * ((d.value ?: 1).toLong()) }
                val fillSource = when (node.op) {
                    UirOpKind.ZEROS -> "[0.0]" + if (numel > 1) " * $numel" else ""
                    UirOpKind.ONES -> "[1.0]" + if (numel > 1) " * $numel" else ""
                    UirOpKind.FULL -> {
                        val fillVal = (node.attributes["fill_value"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: 0.0
                        "[$fillVal]" + if (numel > 1) " * $numel" else ""
                    }
                    UirOpKind.ARANGE -> "list(range($numel))"
                    else -> "[0.0]"
                }
                tensorInitLines.add("""${outputId}_t = helper.make_tensor("${outputId}_v", $onnxDtype, $shapeStr, $fillSource)""")
                val nv = nextNodeVar()
                nodeLines.add(NodeLine(nv, "    $nv = helper.make_node('Constant', inputs=[], outputs=['$outputId'], value=${outputId}_t)"))
                continue
            }

            // ─── 4. Ops needing constant parameter inputs ─────────
            // CLAMP / HARDTANH → Clip(input, min_const, max_const)
            if (node.op == UirOpKind.CLAMP || node.op == UirOpKind.HARDTANH) {
                val minVal = when (node.op) {
                    UirOpKind.CLAMP -> (node.attributes["min"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: -1.0
                    UirOpKind.HARDTANH -> (node.attributes["min_val"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: -1.0
                    else -> -1.0
                }
                val maxVal = when (node.op) {
                    UirOpKind.CLAMP -> (node.attributes["max"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: 1.0
                    UirOpKind.HARDTANH -> (node.attributes["max_val"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: 1.0
                    else -> 1.0
                }
                val minId = "c${outputId}_min"
                val maxId = "c${outputId}_max"
                tensorInitLines.add("""${minId}_t = helper.make_tensor("${minId}_v", $FLOAT, [1], [$minVal])""")
                tensorInitLines.add("""${maxId}_t = helper.make_tensor("${maxId}_v", $FLOAT, [1], [$maxVal])""")
                val nvMin = nextNodeVar()
                val nvMax = nextNodeVar()
                nodeLines.add(NodeLine(nvMin, "    $nvMin = helper.make_node('Constant', inputs=[], outputs=['$minId'], value=${minId}_t)"))
                nodeLines.add(NodeLine(nvMax, "    $nvMax = helper.make_node('Constant', inputs=[], outputs=['$maxId'], value=${maxId}_t)"))
                val nvClip = nextNodeVar()
                nodeLines.add(NodeLine(nvClip, "    $nvClip = helper.make_node('Clip', inputs=['$inputId', '$minId', '$maxId'], outputs=['$outputId'])"))
                valueDtypeMap[outputId] = toOnnxDtype(node.outputs[0].type.dtype.name)
                continue
            }

            // STRIDED_SLICE → Slice(input, starts_const, ends_const, axes_const, steps_const)
            if (node.op == UirOpKind.STRIDED_SLICE) {
                val inputShape = node.inputs.firstOrNull()?.type?.shape
                val ndim = inputShape?.dims?.size ?: 1
                val endsArr = IntArray(ndim) { i ->
                    maxOf(1, ((inputShape?.dims?.getOrNull(i)?.value ?: 1) + 1) / 2)
                }
                val axesArr = (0 until ndim).toList()
                val startsArr = IntArray(ndim) { 0 }
                val stepsArr = IntArray(ndim) { 1 }

                val sId = "c${outputId}_st"
                val eId = "c${outputId}_en"
                val aId = "c${outputId}_ax"
                val stId = "c${outputId}_stp"

                tensorInitLines.add("""${sId}_t = helper.make_tensor("${sId}_v", $INT64, [$ndim], [${startsArr.joinToString(", ")}])""")
                tensorInitLines.add("""${eId}_t = helper.make_tensor("${eId}_v", $INT64, [$ndim], [${endsArr.joinToString(", ")}])""")
                tensorInitLines.add("""${aId}_t = helper.make_tensor("${aId}_v", $INT64, [$ndim], [${axesArr.joinToString(", ")}])""")
                tensorInitLines.add("""${stId}_t = helper.make_tensor("${stId}_v", $INT64, [$ndim], [${stepsArr.joinToString(", ")}])""")

                listOf(sId, eId, aId, stId).forEach { id ->
                    val nv = nextNodeVar()
                    nodeLines.add(NodeLine(nv, "    $nv = helper.make_node('Constant', inputs=[], outputs=['$id'], value=${id}_t)"))
                }
                val nvOp = nextNodeVar()
                nodeLines.add(NodeLine(nvOp, "    $nvOp = helper.make_node('Slice', inputs=['$inputId', '$sId', '$eId', '$aId', '$stId'], outputs=['$outputId'])"))
                valueDtypeMap[outputId] = toOnnxDtype(node.outputs[0].type.dtype.name)
                continue
            }

            // GATHER → Gather(input, indices_const, axis=N)
            if (node.op == UirOpKind.GATHER) {
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: 0
                val iId = "c${outputId}_ix"
                tensorInitLines.add("""${iId}_t = helper.make_tensor("${iId}_v", $INT64, [1], [0])""")
                val nvIx = nextNodeVar()
                nodeLines.add(NodeLine(nvIx, "    $nvIx = helper.make_node('Constant', inputs=[], outputs=['$iId'], value=${iId}_t)"))
                val nvGather = nextNodeVar()
                nodeLines.add(NodeLine(nvGather, "    $nvGather = helper.make_node('Gather', inputs=['$inputId', '$iId'], outputs=['$outputId'], axis=$axis)"))
                valueDtypeMap[outputId] = toOnnxDtype(node.outputs[0].type.dtype.name)
                continue
            }

            // TILE → Tile(input, repeats_const)
            if (node.op == UirOpKind.TILE) {
                val inputShape = node.inputs.firstOrNull()?.type?.shape
                val outputShape = node.outputs.firstOrNull()?.type?.shape
                val ndim = maxOf(inputShape?.dims?.size ?: 1, outputShape?.dims?.size ?: 1)
                val reps = IntArray(ndim) { i ->
                    val inDim = inputShape?.dims?.getOrNull(i)?.value ?: 1
                    val outDim = outputShape?.dims?.getOrNull(i)?.value ?: 1
                    if (inDim > 0 && outDim > 0) maxOf(1, (outDim + inDim / 2) / inDim) else 1
                }
                val rId = "c${outputId}_rep"
                tensorInitLines.add("""${rId}_t = helper.make_tensor("${rId}_v", $INT64, [$ndim], [${reps.joinToString(", ")}])""")
                val nvRep = nextNodeVar()
                nodeLines.add(NodeLine(nvRep, "    $nvRep = helper.make_node('Constant', inputs=[], outputs=['$rId'], value=${rId}_t)"))
                val nvTile = nextNodeVar()
                nodeLines.add(NodeLine(nvTile, "    $nvTile = helper.make_node('Tile', inputs=['$inputId', '$rId'], outputs=['$outputId'])"))
                valueDtypeMap[outputId] = toOnnxDtype(node.outputs[0].type.dtype.name)
                continue
            }

            // ─── 5. Normal ops ────────────────────────────────────
            // For dtype-sensitive binary ops, cast both inputs to float32 first
            @Suppress("EnumValuesSoftDeprecate")
            val binaryFloatOps = setOf(
                UirOpKind.ADD, UirOpKind.SUBTRACT, UirOpKind.MULTIPLY, UirOpKind.DIVIDE,
                UirOpKind.POWER, UirOpKind.MAXIMUM, UirOpKind.MINIMUM,
            )

            // Build input list, casting non-float to float where needed
            val floatInputs = if (node.op in binaryFloatOps && inputIds.size >= 2) {
                // generate Cast nodes for any int-typed inputs
                val castInputs = mutableListOf<String>()
                for (inpId in inputIds) {
                    val dtype = valueDtypeMap[inpId]
                    if (dtype != null && dtype != FLOAT) {
                        val castId = "c${inpId}_f32"
                        val nvCast = nextNodeVar()
                        nodeLines.add(NodeLine(nvCast, "    $nvCast = helper.make_node('Cast', inputs=['$inpId'], outputs=['$castId'], to=$FLOAT)"))
                        castInputs.add(castId)
                    } else {
                        castInputs.add(inpId)
                    }
                }
                castInputs
            } else {
                inputIds.toMutableList()
            }

            val attrs = buildOnnxAttrs(node.op, node.attributes, inputShapes = inputIds.mapNotNull { id ->
                node.inputs.find { it.valueId == id }?.type?.shape
            })
            val onnxInputs = floatInputs.filter { it.isNotEmpty() }.joinToString(", ") { "'$it'" }
            val onnxOutputs = outputIds.joinToString(", ") { "'$it'" }

            val nv = nextNodeVar()
            val callLine = when {
                attrs.isEmpty() -> "    $nv = helper.make_node('$onnxOp', inputs=[$onnxInputs], outputs=[$onnxOutputs])"
                else -> "    $nv = helper.make_node('$onnxOp', inputs=[$onnxInputs], outputs=[$onnxOutputs], $attrs)"
            }
            nodeLines.add(NodeLine(nv, callLine))

            for (outId in outputIds) {
                val dtype = node.outputs.find { it.valueId == outId }?.type?.dtype?.name ?: "float32"
                valueDtypeMap[outId] = toOnnxDtype(dtype)
            }
        }

        // ─── Build Python output ─────────────────────────────────
        builder.appendLine("def run_${funcName}():")
        builder.appendLine("    np.random.seed(42)")

        tensorInitLines.forEach { builder.appendLine("    $it") }

        val inputTensors = mutableListOf<String>()
        for (input in graph.inputs) {
            val shape = input.type.shape
            val shapeStr = shapeToPythonList(shape)
            val dtype = input.type.dtype.name
            val onnxDtype = toOnnxDtype(dtype)
            builder.appendLine("    np_${input.valueId} = np.random.randn(*$shapeStr).astype(np.float32)")
            builder.appendLine("    ${input.valueId}_vi = helper.make_tensor_value_info('${input.valueId}', $onnxDtype, $shapeStr)")
            inputTensors.add("${input.valueId}_vi")
        }

        for (output in graph.outputs) {
            val shape = output.type.shape
            val shapeStr = shapeToPythonList(shape)
            val dtype = output.type.dtype.name
            val onnxDtype = toOnnxDtype(dtype)
            builder.appendLine("    ${output.valueId}_vi = helper.make_tensor_value_info('${output.valueId}', $onnxDtype, $shapeStr)")
            outputTensors.add("${output.valueId}_vi")
        }

        builder.appendLine()
        val nodeVarNames = nodeLines.joinToString(", ") { it.varName }
        nodeLines.forEach { builder.appendLine(it.code) }
        builder.appendLine()

        builder.appendLine("    _graph = helper.make_graph([$nodeVarNames], '$funcName', [${inputTensors.joinToString(", ")}], [${outputTensors.joinToString(", ")}])")
        builder.appendLine("    _model = helper.make_model(_graph, opset_imports=[helper.make_opsetid('', $opsetVersion)])")
        builder.appendLine()
        val inputFeed = graph.inputs.joinToString(", ") { "'${it.valueId}': np_${it.valueId}" }
        builder.appendLine("    _sess = ort.InferenceSession(_model.SerializeToString())")
        builder.appendLine("    _result = _sess.run(None, {$inputFeed})")
        builder.appendLine()
        builder.appendLine("    if len(_result) == 1:")
        builder.appendLine("        print(f\"[ONNX-OUT] ${funcName}: shape={list(_result[0].shape)}\")")
        builder.appendLine("    else:")
        builder.appendLine("        for _i, _r in enumerate(_result):")
        builder.appendLine("            print(f\"[ONNX-OUT] ${funcName}[{_i}]: shape={list(_r.shape)}\")")
        builder.appendLine()
        builder.appendLine()
        builder.appendLine("run_${funcName}()")
    }

    // ────────────────────────────────────────────────────────────────
    // Compound ops — generate multiple ONNX nodes
    // ────────────────────────────────────────────────────────────────
    private fun translateCompoundOp(
        node: UirNode, outputId: String, inputId: String?,
        tensorInitLines: MutableList<String>,
        nodeLines: MutableList<NodeLine>,
        valueDtypeMap: MutableMap<String, String>,
    ) {
        val inputId = inputId ?: outputId
        val dtype = node.outputs[0].type.dtype.name
        val onnxDtype = toOnnxDtype(dtype)
        valueDtypeMap[outputId] = onnxDtype

        when (node.op) {
            UirOpKind.GELU -> {
                // GELU = 0.5 * x * (1 + erf(x / sqrt(2)))
                val halfId = "c${outputId}_h"
                val oneId = "c${outputId}_o"
                val sqrt2Id = "c${outputId}_sq2"
                tensorInitLines.add("""${halfId}_t = helper.make_tensor("${halfId}_v", $FLOAT, [1], [0.5])""")
                tensorInitLines.add("""${oneId}_t = helper.make_tensor("${oneId}_v", $FLOAT, [1], [1.0])""")
                tensorInitLines.add("""${sqrt2Id}_t = helper.make_tensor("${sqrt2Id}_v", $FLOAT, [1], [1.4142135623730951])""")

                listOf(halfId, oneId, sqrt2Id).forEach { id ->
                    val nv = nextNodeVar()
                    nodeLines.add(NodeLine(nv, "    $nv = helper.make_node('Constant', inputs=[], outputs=['$id'], value=${id}_t)"))
                }

                val dId = "t${outputId}_div"
                val eId = "t${outputId}_erf"
                val aId = "t${outputId}_add"
                val mId = "t${outputId}_mul"

                val nvD = nextNodeVar(); nodeLines.add(NodeLine(nvD, "    $nvD = helper.make_node('Div', inputs=['$inputId', '$sqrt2Id'], outputs=['$dId'])"))
                val nvE = nextNodeVar(); nodeLines.add(NodeLine(nvE, "    $nvE = helper.make_node('Erf', inputs=['$dId'], outputs=['$eId'])"))
                val nvA = nextNodeVar(); nodeLines.add(NodeLine(nvA, "    $nvA = helper.make_node('Add', inputs=['$oneId', '$eId'], outputs=['$aId'])"))
                val nvM = nextNodeVar(); nodeLines.add(NodeLine(nvM, "    $nvM = helper.make_node('Mul', inputs=['$halfId', '$aId'], outputs=['$mId'])"))
                val nvOut = nextNodeVar(); nodeLines.add(NodeLine(nvOut, "    $nvOut = helper.make_node('Mul', inputs=['$inputId', '$mId'], outputs=['$outputId'])"))
            }
            UirOpKind.SILU -> {
                // SILU = x * sigmoid(x)
                val sId = "t${outputId}_sig"
                val nvS = nextNodeVar()
                nodeLines.add(NodeLine(nvS, "    $nvS = helper.make_node('Sigmoid', inputs=['$inputId'], outputs=['$sId'])"))
                val nvOut = nextNodeVar()
                nodeLines.add(NodeLine(nvOut, "    $nvOut = helper.make_node('Mul', inputs=['$inputId', '$sId'], outputs=['$outputId'])"))
            }
            UirOpKind.MISH -> {
                // MISH = x * tanh(log(1 + exp(x)))
                val oneId = "c${outputId}_o"
                tensorInitLines.add("""${oneId}_t = helper.make_tensor("${oneId}_v", $FLOAT, [1], [1.0])""")
                val nvOne = nextNodeVar()
                nodeLines.add(NodeLine(nvOne, "    $nvOne = helper.make_node('Constant', inputs=[], outputs=['$oneId'], value=${oneId}_t)"))

                val eId = "t${outputId}_exp"
                val aId = "t${outputId}_add"
                val lId = "t${outputId}_log"
                val tId = "t${outputId}_tan"

                val nvE = nextNodeVar(); nodeLines.add(NodeLine(nvE, "    $nvE = helper.make_node('Exp', inputs=['$inputId'], outputs=['$eId'])"))
                val nvA = nextNodeVar(); nodeLines.add(NodeLine(nvA, "    $nvA = helper.make_node('Add', inputs=['$oneId', '$eId'], outputs=['$aId'])"))
                val nvL = nextNodeVar(); nodeLines.add(NodeLine(nvL, "    $nvL = helper.make_node('Log', inputs=['$aId'], outputs=['$lId'])"))
                val nvT = nextNodeVar(); nodeLines.add(NodeLine(nvT, "    $nvT = helper.make_node('Tanh', inputs=['$lId'], outputs=['$tId'])"))
                val nvOut = nextNodeVar(); nodeLines.add(NodeLine(nvOut, "    $nvOut = helper.make_node('Mul', inputs=['$inputId', '$tId'], outputs=['$outputId'])"))
            }
            UirOpKind.RSQRT -> {
                // RSQRT = 1 / sqrt(x)
                val sId = "t${outputId}_sq"
                val nvS = nextNodeVar()
                nodeLines.add(NodeLine(nvS, "    $nvS = helper.make_node('Sqrt', inputs=['$inputId'], outputs=['$sId'])"))
                val nvOut = nextNodeVar()
                nodeLines.add(NodeLine(nvOut, "    $nvOut = helper.make_node('Reciprocal', inputs=['$sId'], outputs=['$outputId'])"))
            }
            UirOpKind.LOG2 -> {
                // LOG2 = log(x) / log(2)
                val log2cId = "c${outputId}_l2"
                tensorInitLines.add("""${log2cId}_t = helper.make_tensor("${log2cId}_v", $FLOAT, [1], [0.6931471805599453])""")
                val nvC = nextNodeVar()
                nodeLines.add(NodeLine(nvC, "    $nvC = helper.make_node('Constant', inputs=[], outputs=['$log2cId'], value=${log2cId}_t)"))
                val lId = "t${outputId}_log"
                val nvL = nextNodeVar()
                nodeLines.add(NodeLine(nvL, "    $nvL = helper.make_node('Log', inputs=['$inputId'], outputs=['$lId'])"))
                val nvOut = nextNodeVar()
                nodeLines.add(NodeLine(nvOut, "    $nvOut = helper.make_node('Div', inputs=['$lId', '$log2cId'], outputs=['$outputId'])"))
            }
            UirOpKind.ARGMAX, UirOpKind.ARGMIN -> {
                // ArgMax/ArgMin → native op + Cast(float32)
                val rawId = "t${outputId}_raw"
                val axis = (node.attributes["axis"] as? UirIntAttr)?.value ?: -1
                val onnxName = if (node.op == UirOpKind.ARGMAX) "ArgMax" else "ArgMin"
                // 标量输入时 ONNX Runtime 不允许任何 axis（因为 rank=0 时合法区间为空）
                // → 直接输出常数 0.0（单元素的 argmin/argmax 的结果就是 0）
                val inputShape = node.inputs.firstOrNull()?.type?.shape
                val isScalar = inputShape != null && inputShape.dims.size == 0
                if (isScalar) {
                    tensorInitLines.add("""${outputId}_t = helper.make_tensor("${outputId}_v", $FLOAT, [], [0.0])""")
                    val nvConst = nextNodeVar()
                    nodeLines.add(NodeLine(nvConst, "    $nvConst = helper.make_node('Constant', inputs=[], outputs=['$outputId'], value=${outputId}_t)"))
                } else {
                    val nvRaw = nextNodeVar()
                    nodeLines.add(NodeLine(nvRaw, "    $nvRaw = helper.make_node('$onnxName', inputs=['$inputId'], outputs=['$rawId'], axis=$axis, keepdims=0)"))
                    val nvCast = nextNodeVar()
                    nodeLines.add(NodeLine(nvCast, "    $nvCast = helper.make_node('Cast', inputs=['$rawId'], outputs=['$outputId'], to=$FLOAT)"))
                }
            }
            else -> {
                // Unreachable
            }
        }
    }

    // ────────────────────────────────────────────────────────────────
    // Attribute builder (only for ops keeping attrs in opset 11+)
    // ────────────────────────────────────────────────────────────────
    private fun buildOnnxAttrs(op: UirOpKind, attrs: Map<String, Attribute>, inputShapes: List<UirShape>): String {
        val p = mutableListOf<String>()
        when (op) {
            UirOpKind.LEAKY_RELU -> p.add("alpha=${(attrs["negative_slope"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: 0.01}")
            UirOpKind.ELU -> p.add("alpha=${(attrs["alpha"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: 1.0}")
            UirOpKind.SOFTMAX, UirOpKind.LOG_SOFTMAX -> p.add("axis=${(attrs["axis"] as? UirIntAttr)?.value ?: -1}")
            UirOpKind.TRANSPOSE -> {
                val nd = inputShapes.firstOrNull()?.dims?.size ?: 2
                if (nd >= 2) p.add("perm=[${(0 until nd).map { i -> when(i){nd-2->nd-1;nd-1->nd-2;else->i} }.joinToString(", ")}]")
            }
            UirOpKind.CONCAT -> p.add("axis=${(attrs["axis"] as? UirIntAttr)?.value ?: 0}")
            UirOpKind.GATHER -> p.add("axis=${(attrs["axis"] as? UirIntAttr)?.value ?: 0}")
            UirOpKind.CAST -> p.add("to=${toOnnxDtype((attrs["dtype"] as? UirStringAttr)?.value ?: "float32")}")
            // Reduce ops: axes as attribute (opset 11)
            UirOpKind.REDUCE_SUM, UirOpKind.REDUCE_MEAN, UirOpKind.REDUCE_MAX, UirOpKind.REDUCE_MIN -> {
                val axis = (attrs["axis"] as? UirIntAttr)?.value ?: -1
                val kd = (attrs["keepdims"] as? UirIntAttr)?.value?.let { it != 0 } ?: false
                p.add("axes=[$axis]"); p.add("keepdims=${kd.toString().replaceFirstChar { it.uppercase() }}")
            }
            // Unsqueeze/Squeeze: axes as attribute (opset 11)
            UirOpKind.UNSQUEEZE, UirOpKind.EXPAND_DIMS -> p.add("axes=[${(attrs["axis"] as? UirIntAttr)?.value ?: 0}]")
            UirOpKind.SQUEEZE -> {
                val inputShape = inputShapes.firstOrNull()
                val ndim = inputShape?.dims?.size ?: 1
                val squeezeDims = (0 until ndim).filter { i ->
                    inputShape?.dims?.getOrNull(i)?.value == 1
                }
                if (squeezeDims.isNotEmpty()) p.add("axes=[${squeezeDims.joinToString(", ")}]")
            }
            UirOpKind.CONV2D -> {
                val s = (attrs["stride"] as? UirIntAttr)?.value ?: 1
                val pd = (attrs["padding"] as? UirIntAttr)?.value ?: 0
                val d = (attrs["dilation"] as? UirIntAttr)?.value ?: 1
                val g = (attrs["groups"] as? UirIntAttr)?.value ?: 1
                p.add("strides=[$s, $s]"); p.add("pads=[$pd, $pd, $pd, $pd]")
                p.add("dilations=[$d, $d]"); p.add("group=$g")
            }
            UirOpKind.MAX_POOL2D, UirOpKind.AVG_POOL2D -> {
                val k = (attrs["kernel_size"] as? UirIntAttr)?.value ?: 2
                val s = (attrs["stride"] as? UirIntAttr)?.value ?: k
                val pd = (attrs["padding"] as? UirIntAttr)?.value ?: 0
                p.add("kernel_shape=[$k, $k]"); p.add("strides=[$s, $s]"); p.add("pads=[$pd, $pd, $pd, $pd]")
            }
            UirOpKind.CUMSUM -> p.add("axis=${(attrs["axis"] as? UirIntAttr)?.value ?: -1}")
            UirOpKind.SELU -> {
                p.add("alpha=${(attrs["alpha"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: 1.67326}")
                p.add("gamma=${(attrs["gamma"] as? UirStringAttr)?.value?.toDoubleOrNull() ?: 1.0507}")
            }
            else -> {}
        }
        return p.joinToString(", ")
    }

    // ────────────────────────────────────────────────────────────────
    // Op → ONNX op name mapping
    // ────────────────────────────────────────────────────────────────
    @Suppress("EnumValuesSoftDeprecate")
    private fun opToOnnx(op: UirOpKind): String? = when (op) {
        // ─── Activation ────────────────────────────────
        UirOpKind.RELU -> "Relu"
        UirOpKind.LEAKY_RELU -> "LeakyRelu"
        UirOpKind.ELU -> "Elu"
        UirOpKind.SELU -> "Selu"
        UirOpKind.SIGMOID -> "Sigmoid"
        UirOpKind.TANH -> "Tanh"
        UirOpKind.SOFTMAX -> "Softmax"
        UirOpKind.LOG_SOFTMAX -> "LogSoftmax"
        UirOpKind.HARDTANH -> null  // handled via inputParamOps
        UirOpKind.CLAMP -> null     // handled via inputParamOps

        // ─── Compound ──────────────────────────────────
        UirOpKind.GELU -> null
        UirOpKind.SILU -> null
        UirOpKind.MISH -> null
        UirOpKind.RSQRT -> null
        UirOpKind.LOG2 -> null

        // ─── Unary math ────────────────────────────────
        UirOpKind.NEG -> "Neg"
        UirOpKind.ABS -> "Abs"
        UirOpKind.SIGN -> "Sign"
        UirOpKind.EXP -> "Exp"
        UirOpKind.LOG -> "Log"
        UirOpKind.SQRT -> "Sqrt"
        UirOpKind.RECIPROCAL -> "Reciprocal"
        UirOpKind.CEIL -> "Ceil"
        UirOpKind.FLOOR -> "Floor"
        UirOpKind.ROUND -> "Round"

        // ─── Binary ────────────────────────────────────
        UirOpKind.POWER -> "Pow"
        UirOpKind.ADD -> "Add"
        UirOpKind.SUBTRACT -> "Sub"
        UirOpKind.MULTIPLY -> "Mul"
        UirOpKind.DIVIDE -> "Div"
        UirOpKind.MAXIMUM -> "Max"
        UirOpKind.MINIMUM -> "Min"

        // ─── Reduce ────────────────────────────────────
        UirOpKind.REDUCE_SUM -> "ReduceSum"
        UirOpKind.REDUCE_MEAN -> "ReduceMean"
        UirOpKind.REDUCE_MAX -> "ReduceMax"
        UirOpKind.REDUCE_MIN -> "ReduceMin"
        UirOpKind.ARGMAX -> null  // compound: ArgMax + Cast
        UirOpKind.ARGMIN -> null  // compound: ArgMin + Cast

        // ─── Shape ──────────────────────────────────────
        UirOpKind.RESHAPE -> "Reshape"
        UirOpKind.TRANSPOSE -> "Transpose"
        UirOpKind.SQUEEZE -> "Squeeze"
        UirOpKind.UNSQUEEZE -> "Unsqueeze"
        UirOpKind.EXPAND_DIMS -> "Unsqueeze"
        UirOpKind.CONCAT -> "Concat"
        UirOpKind.SPLIT -> "Split"

        // ─── Indexing ──────────────────────────────────
        UirOpKind.GATHER -> null        // special const-input handler
        UirOpKind.STRIDED_SLICE -> null // special const-input handler
        UirOpKind.TILE -> null          // special const-input handler
        UirOpKind.TRIL -> null
        UirOpKind.TRIU -> null
        UirOpKind.BROADCAST_TO -> null

        // ─── Cumulative ────────────────────────────────
        UirOpKind.CUMSUM -> null
        UirOpKind.CUMPROD -> null

        // ─── Cast ──────────────────────────────────────
        UirOpKind.CAST -> "Cast"

        // ─── NN ────────────────────────────────────────
        UirOpKind.CONV2D -> "Conv"
        UirOpKind.MAX_POOL2D -> "MaxPool"
        UirOpKind.AVG_POOL2D -> "AveragePool"
        UirOpKind.MATMUL -> "MatMul"

        // ─── Norm ──────────────────────────────────────
        UirOpKind.LAYER_NORM -> null
        UirOpKind.BATCH_NORM -> null

        // ─── Interp ────────────────────────────────────
        UirOpKind.INTERPOLATE -> null
        UirOpKind.RESIZE2D -> null

        // ─── Constants (handled separately) ────────────
        UirOpKind.FULL -> null
        UirOpKind.ZEROS -> null
        UirOpKind.ONES -> null
        UirOpKind.ARANGE -> null
    }

    private fun shapeToPythonList(shape: UirShape): String {
        if (shape.dims.isEmpty()) return "[]"
        return shape.dims.joinToString(", ") { dim ->
            when (dim.dimKind) { UirDimKind.CONSTANT -> dim.value?.toString() ?: "1" else -> "1" }
        }.let { "[$it]" }
    }
}
